### ISSUE TITLE
cellsketch-add-mask

### ISSUE THREAD

**Issue by redven** [betaseg/cellsketch#2]
Hi, super excited to play around with CellSketch!!!
When trying to add the mitochondria mask from your provided dataset, I get this response:

16:33:52 INFO ~ Cellsketch-add-mask is started.
16:33:54 INFO ~ "#ffffff" is not a valid value for "--color".
16:33:54 INFO ~
16:33:54 INFO ~ Example: java en.frauzufall.cellsketch.command.AddMask
16:33:55 INFO ~ Terminates cellsketch-add-mask

And the n5 project file remains unchanged.
Any idea what i am doing wrong? Much appreciated.
Stefan

**Comment by frauzufall** [comment]
Hi @redven, thank you for reporting this and sorry for responding so late, I somehow missed the notification for this issue :(  
the color has to be provided in a different format (RGBA, i.e. "255:255:0:255") and the default value for `color in the solution didn't match this format - we fixed the issue and actually moved the next versions the solutions to a separate betaseg-solutions catalog - please check out https://github.com/betaseg/cellsketch/blob/main/GUIDE_QUICKSTART.md for updated instructions. Thank you for being an early tester and sorry for the trouble.
